<?php
// Generated by ZF2's ./bin/classmap_generator.php @ Sun, 15 Jan 2012 19:46:42 -0700
return array(
    'AdfabUser\Module'                            => __DIR__ . '/Module.php',
    'AdfabUser\Event\ResolveTargetEntityListener' => __DIR__ . '/src/AdfabUser/Event/ResolveTargetEntityListener.php',
    'AdfabUser\Mapper\UserMetaDoctrine'           => __DIR__ . '/src/AdfabUser/Mapper/UserMetaDoctrine.php',
    'AdfabUser\Mapper\UserDoctrine'               => __DIR__ . '/src/AdfabUser/Mapper/UserDoctrine.php',
    'AdfabUser\Entity\UserMappedSuperClass'       => __DIR__ . '/src/AdfabUser/Entity/UserMappedSuperClass.php',
    'AdfabUser\Entity\UserMetaMappedSuperClass'   => __DIR__ . '/src/AdfabUser/Entity/UserMetaMappedSuperClass.php',
    'AdfabUser\Entity\UserMeta'                   => __DIR__ . '/src/AdfabUser/Entity/UserMeta.php',
    'AdfabUser\Entity\User'                       => __DIR__ . '/src/AdfabUser/Entity/User.php',
);
